arch:
  - arm64

language: python
python:
  - "3.9.16"

env:
  - IMGNAME=golub/ubuntu:dbot

services:
  - docker

before_install:
- docker image build -t ${IMGNAME} .

before_script:
- python3 --version
script:
#  - dig +short myip.opendns.com @resolver1.opendns.com
- python3 -m pytest

after_success:
- docker login -u ${DHUB_USERNAME} -p ${DHUB_PASS}
- echo "...Moving code to the production...."
