arch:
  - arm64

env:
  - IMGNAME=golub/ubuntu:dbot

services:
  - docker

before_install:
- docker image build -t ${IMGNAME} .

before_script:
- python3 --version
script:
- pip3 install pytest
- python3 -m pytest
after_success:
- docker login -u ${DHUB_USERNAME} -p ${DHUB_PASS}
- python3 moveToProduction.py 
